services:
  code-server:
    image: codercom/code-server:4.107.0-39
    container_name: code-server
    restart: unless-stopped
    ports:
      - "8082:8080"  # Puerto 8081 para correr el servicio
    environment:
      PASSWORD: ${PASSWORD}
    volumes:
      - ./projects:/home/coder/project
      - ./code-server-data:/home/coder/.local/share/code-server 
    command: --auth password /home/coder/projects
    tty: true
    stdin_open: true