services:
  code-server:
    image: codercom/code-server:4.107.0-39
    container_name: code-server
    restart: unless-stopped
    ports:
      - "8082:8080"  # Puerto 8082 para correr el servicio
      - "4200:4200"  # Puerto 4201 para Angular aplicación 1
      - "4201:4200"  # Puerto 4202 para Angular aplicación 2
      - "3002:3002"  # Puerto 3002 para Node.js aplicación 1
      - "3003:3003"  # Puerto 3003 para Node.js aplicación 2
      - "3004:3004"  # Puerto 3004 para Node.js aplicación 3
      - "3005:3005"  # Puerto 3005 para Node.js aplicación 4
      - "3006:3006"  # Puerto 3006 para Node.js aplicación 5
    environment:
      PASSWORD: ${PASSWORD}
    volumes:
      - ./projects:/home/coder/projects
      - ./code-server-data:/home/coder/.local/share/code-server 
    command: --auth password /home/coder/projects
    tty: true
    stdin_open: true